export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
