export const FETCH_INVOICES = 'FETCH_INVOICES';
export const SET_INVOICE = 'SET_INVOICE';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
