export const FETCH_SERVICEORDERS = 'FETCH_SERVICEORDERS';
export const SET_SERVICEORDER = 'SET_SERVICEORDER';
export const CREATE_SERVICEORDER = 'CREATE_SERVICEORDER';
export const UPDATE_SERVICEORDER = 'UPDATE_SERVICEORDER';
export const DELETE_SERVICEORDER = 'DELETE_SERVICEORDER';
